export const DB_CONNECTION = 'DATABASE_CONNECTION';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_CHARACTERISTIC_REPOSITORY = 'PRODUCT_CHARACTERISTIC_REPOSITORY';
