export const DB_CONNECTION = 'DATABASE_CONNECTION';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_CHARACTERISTIC_REPOSITORY = 'PRODUCT_CHARACTERISTIC_REPOSITORY';
export const BASKET_REPOSITORY = 'BASKET_REPOSITORY';
export const BASKET_LINE_ITEM_REPOSITORY = 'BASKET_LINE_ITEM_REPOSITORY';
export const STORE_REPOSITORY = 'STORE_REPOSITORY';
export const PAYMENT_METHOD_REPOSITORY = 'PAYMENT_METHOD';

